### ISSUE TITLE
希望支持 open-vsx

### ISSUE THREAD

**Issue by EdwardChoHub** [ModyQyW/uni-helper#15]

**Comment by ModyQyW** [comment]
现在哪部分不兼容呢？

**Comment by ModyQyW** [comment]
不可用的插件应该会有提示。

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/31850793/178661542-2ac843d2-481d-41e6-959a-b4ac032c9ba3.png">

目前来看，这个仓库内所有 vscode 插件都兼容 vscode for web。

<img width="450" alt="image" src="https://user-images.githubusercontent.com/31850793/178661635-c4fae063-6ece-4b11-b05a-0baa599bb656.png">

**Comment by EdwardChoHub** [comment]
code-server: v4.4.0
Code: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-21T22:01:21.152Z (3 wks ago)
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36

CodeServer上是搜索不到，有可能是版本问题

**Comment by ModyQyW** [comment]
code-server 对这方面有明确的解释：https://coder.com/docs/code-server/latest/FAQ#why-cant-code-server-use-microsofts-extension-marketplace

短时间内我没有时间做 open-vsx 支持，欢迎 PR

**Comment by EdwardChoHub** [comment]
感谢

**Comment by ModyQyW** [comment]
https://github.com/open-vsx/publish-extensions/pull/619

**Comment by EdwardChoHub** [comment]
感谢

**Comment by ModyQyW** [comment]
明天我会试着在这个仓库接入一下

**Comment by ModyQyW** [comment]
<img width="1521" alt="image" src="https://user-images.githubusercontent.com/31850793/178746641-ab66b7f0-da20-43c7-96f8-03a5cf4fc58f.png">

现在已经有插件了。

Namespace 正在申请：https://github.com/EclipseFdn/open-vsx.org/issues/1124

**Comment by ModyQyW** [comment]
Namespace 已经通过了。我认为一切都已经就绪了。如果还有新的问题，可以考虑开一个新的 issue。谢谢 :D

**Comment by EdwardChoHub** [comment]
CodeServer中已经有了，非常感谢🙏
