### ISSUE TITLE
templete中大写可以识别，小写不行

### ISSUE THREAD

**Issue by ywenhao** [ModyQyW/uni-helper#28]
### Describe the bug
描述问题

小写才能识别，但是小写页面上才能正常显示。
![image](https://user-images.githubusercontent.com/37856060/191402810-b2c2e56d-c500-45df-82a5-eb0783f1ea46.png)
![image](https://user-images.githubusercontent.com/37856060/191402845-313749c4-629f-40bb-ae9b-44d7e1a2e858.png)
![image](https://user-images.githubusercontent.com/37856060/191402868-0dd4f262-16f8-481c-a79f-b8a8fb0e54e9.png)

![image](https://user-images.githubusercontent.com/37856060/191402977-3dc2041b-be9f-4010-a113-3eb9809b67cb.png)

### Reproduction
复现

安装正常使用，vscode 编辑模式下查看

### System Info
系统信息

```Shell
vscode + volar
```

### Used Package Manager
使用的包管理器

yarn

### Validations
核对

- [X] Follow our [Code of Conduct](https://github.com/ModyQyW/.github/blob/main/CODE_OF_CONDUCT.md)
遵循我们的 [行为准则](https://github.com/ModyQyW/.github/blob/main/CODE_OF_CONDUCT.md)

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
检查是否已经有一个报告相同错误的问题，以避免重复创建。

- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
这是一个具体的错误。如有疑问，请开启 GitHub 讨论。

- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
昨天有一个类似的 ISSUE https://github.com/ModyQyW/uni-helper/issues/27。

如果 Volar 没有配置错误（需要安装 TypeScript Vue Plugin 或者开启 Take Over Mode），还需要在 `tsconfig.json` 里补充以下内容。

```json
{
  "vueCompilerOptions": {
    "experimentalRuntimeMode": "runtime-uni-app"
  }
}
```

这点是刚刚才确认的，过一会我会补充 README。造成的不便非常抱歉。

**Comment by ModyQyW** [comment]
我已经为 uni-app-types、uni-cloud-types 和 uni-ui-types 发布了新版本，请试着调整一下 `tsconfig.json` 确认问题是否已经解决。

**Comment by ModyQyW** [comment]
@ywenhao 请问调整 `tsconfig.json` 后还有问题吗？

**Comment by ModyQyW** [comment]
无响应，暂时先关闭 ISSUE。

**Comment by ywenhao** [comment]
> 无响应，暂时先关闭 ISSUE。

可以了 up主 , 感觉volar 本身感觉有点问题 ，type 有代码提示了。 open-type这个没有代码提示，但是有错误校验。
![image](https://user-images.githubusercontent.com/37856060/196704019-e6e8f355-006f-4cf4-a4bb-1da7bb46c96d.png)

**Comment by ModyQyW** [comment]
emmmm 我这里连 `type` 的代码提示也没有，但我确认过 `type` 和 `open-type` 我都有提供类型，感觉更像是 volar 没提示出来的问题。

UP 主可还行，我目前没发过技术类视频哦，如果看到 B 站上有人用我的名义发视频，谨防诈骗哈。
