### ISSUE TITLE
uni-app js 条件编译是错误的

### ISSUE THREAD

**Issue by inoryxun** [ModyQyW/uni-helper#31]
### Additional context
额外上下文

<img width="911" alt="image" src="https://user-images.githubusercontent.com/16499387/191690475-3a3dac00-0a5a-4900-be91-6f9378d3429a.png">
正确的应该是这个
// #ifdef  %PLATFORM%
平台特有的API实现
// #endif

**Comment by ModyQyW** [comment]
感谢指出。vscode-uni-app-snippets v0.9.3 应该已经修复了这个问题。
