### ISSUE TITLE
只启用volar的时候不能使用，只能依赖vetur使用

### ISSUE THREAD

**Issue by ch1xxx** [ModyQyW/uni-helper#5]

**Comment by ModyQyW** [comment]
volar 相关说明见 https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features。

已知 volar 不能和 vetur 共用，想使用 volar 需要禁用 vetur。

另外，vscode 安装、启用、禁用任意插件后，为确保生效需要重启 vscode。

如果以上不能解决你的问题，请发复现 repo 和 vscode 配置。

**Comment by ModyQyW** [comment]
目前觉得是类似于 <https://github.com/johnsoncodehk/volar/issues/19> 的问题。目前增加了 language 试着解决这个问题。

**Comment by ch1xxx** [comment]
已解决，感谢！
