### ISSUE TITLE
subNVues  类型出错

### ISSUE THREAD

**Issue by sc32024826** [ModyQyW/uni-helper#57]
### Describe the bug
描述问题

官网文档中 虽然subNVues  标明是一个Object 类型,但是实际上需要传的是`Array<Object>`, 可以参考官网的具体示例
[`https://uniapp.dcloud.net.cn/collocation/pages.html#app-subnvues`](https://uniapp.dcloud.net.cn/collocation/pages.html#app-subnvues)
``` jsonc
"subNVues":[{//侧滑菜单
	"id": "drawer", //subNVue 的 id，可通过 uni.getSubNVueById('drawer') 获取
	"path": "pages/index/drawer.nvue", // nvue 路径
	"style": { //webview style 子集，文档可暂时开放出来位置，大小相关配置
		"position": "popup", //除 popup 外，其他值域参考 5+ webview position 文档
		"width": "50%"
	}

}, {//弹出层
	"id": "popup",
	"path": "pages/index/popup",
	"style": {
		"position": "popup",
		"margin":"auto",
		"width": "150px",
		"height": "150px"
	}

}, {//自定义头
	"id": "nav",
	"path": "pages/index/nav",
	"style": {
		"position": "dock",
		"height": "44px"
	}

}]
```

### Reproduction
复现

, 虽然只是个警告 但是逼死强迫症 

### System Info
系统信息

```Shell
无
```

### Used Package Manager
使用的包管理器

yarn

### Validations
核对

- [X] Follow our [Code of Conduct](https://github.com/ModyQyW/.github/blob/main/CODE_OF_CONDUCT.md)
遵循我们的 [行为准则](https://github.com/ModyQyW/.github/blob/main/CODE_OF_CONDUCT.md)

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
检查是否已经有一个报告相同错误的问题，以避免重复创建。

- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
这是一个具体的错误。如有疑问，请开启 GitHub 讨论。

- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
非常感谢指出！已经在 v0.8.4 修复了这个问题。

Array 也是 Object，这波只能说是我大意了😅
