### ISSUE TITLE
uni-ui-types  类型提示未生效

### ISSUE THREAD

**Issue by rocwinds** [ModyQyW/uni-helper#74]
### 描述问题

安装uni-ui-types，在vscode中uni-ui组件的属性没有类型提示
<img width="867" alt="image" src="https://user-images.githubusercontent.com/59724541/198812476-afe5c64a-8b8f-49c1-94a3-19cf3f12e585.png">
![image](https://user-images.githubusercontent.com/59724541/198812519-69b62328-eed7-402b-8f7b-f7137c78d361.png)

### 复现

安装uni-ui-types，在vscode中调用uni-ui组件时，组件属性没有显示具体的类型提示

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 AMD Ryzen 5 5600H with Radeon Graphics
    Memory: 2.35 GB / 15.37 GB
  Binaries:
    Node: 14.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.18 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.16 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (106.0.1370.52)
    Internet Explorer: 11.0.22000.120
```

### 使用的包管理器

yarn

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/ModyQyW/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
方便看一下这张图的报错吗？我这边没报错，可能是哪里配置有问题了，想看看你那边的报错是哪里报的

EDIT: 应该是 import/no-unresolved 报的错

**Comment by ModyQyW** [comment]
0.1.5 已经修复了这个报错啦，非常感谢你指出这个问题 👍🏻
