### ISSUE TITLE
使用ts+vue开发uniapp，安装此插件和volar无法识别view和text标签

### ISSUE THREAD

**Issue by liu-xinhui** [ModyQyW/uni-helper#9]
请问下，有啥好办法解决吗
<img width="553" alt="image" src="https://user-images.githubusercontent.com/7698511/165913384-f9da361b-0eb5-4e21-8da7-1ff9c9d577bc.png">

**Comment by ModyQyW** [comment]
无法识别 view 和 text 标签是什么意思？期望 view 和 text 和 div 着色之类的一样嘛？

**Comment by liu-xinhui** [comment]
@ModyQyW 是的，能识别的是蓝色

**Comment by ModyQyW** [comment]
我看一下，插件不一定能做这个

**Comment by ModyQyW** [comment]
我觉得这不是这个插件可以做的事情。我试着换了主题，发现在某些主题下，颜色是一致的。

<img width="345" alt="image" src="https://user-images.githubusercontent.com/31850793/165917649-99e43d26-4432-4c15-9476-ebf07eabb8a7.png">

可能到这些主题的 repo 提一下 issue 或者魔改一下主题才是正解。如果查到了更好的说明或文档，可以贴个链接，我看一下能不能做。

**Comment by liu-xinhui** [comment]
好的，也没啥影响，就是看着不爽，老感觉是报错的
